(() => {
  const loginView=document.querySelector('#login-view'),dashboard=document.querySelector('#dashboard'),loginForm=document.querySelector('#login-form'),loginStatus=document.querySelector('#login-status'),list=document.querySelector('#admin-list'),dialog=document.querySelector('#vehicle-dialog'),form=document.querySelector('#vehicle-form'),formStatus=document.querySelector('#form-status'),preview=document.querySelector('#image-preview');
  let vehicles=[];
  const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const euro=v=>new Intl.NumberFormat('it-IT',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(Number(v||0));
  async function api(url,options={}){const r=await fetch(url,options);const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||'Operazione non riuscita');return data}
  async function check(){try{await api('/api/admin/session');showDashboard();await load()}catch{loginView.hidden=false;dashboard.hidden=true}}
  function showDashboard(){loginView.hidden=true;dashboard.hidden=false}
  loginForm.addEventListener('submit',async e=>{e.preventDefault();loginStatus.textContent='Accesso in corso...';try{await api('/api/admin/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(new FormData(loginForm)))});showDashboard();await load()}catch(err){loginStatus.textContent=err.message}})
  document.querySelector('#logout').onclick=async()=>{await api('/api/admin/logout',{method:'POST'});location.reload()};
  async function load(){vehicles=await api('/api/admin/vehicles');render()}
  function render(){document.querySelector('#total-count').textContent=vehicles.length;document.querySelector('#active-count').textContent=vehicles.filter(v=>v.active).length;document.querySelector('#reserved-count').textContent=vehicles.filter(v=>v.status==='reserved').length;if(!vehicles.length){list.innerHTML='<div class="empty-admin">Non hai ancora inserito auto a noleggio.</div>';return}list.innerHTML=vehicles.map(v=>`<article class="admin-car"><img src="${esc(v.images?.[0]||'assets/auto-placeholder.svg')}" alt=""><div><h3>${esc(v.brand)} ${esc(v.model)} <span class="badge ${v.status==='reserved'?'reserved':''}">${v.status==='reserved'?'Prenotata':'Disponibile'}</span>${!v.active?'<span class="badge hidden">Nascosta</span>':''}</h3><p>${esc(v.category||'Auto a noleggio')} · ${esc(v.fuel||'Alimentazione non indicata')} · ${esc(v.transmission||'Cambio non indicato')}</p><span class="price">${euro(v.price)} / ${esc(v.priceUnit||'mese')}</span></div><div class="car-actions"><button data-edit="${v.id}">Modifica</button><button class="delete" data-delete="${v.id}">Elimina</button></div></article>`).join('')}
  function openNew(){form.reset();form.elements.id.value='';form.active.checked=true;preview.innerHTML='';document.querySelector('#modal-kicker').textContent='NUOVA AUTO';document.querySelector('#modal-title').textContent='Inserisci un’auto';dialog.showModal()}
  function openEdit(v){form.reset();for(const [k,val] of Object.entries(v)){if(form.elements[k]&&k!=='images'){if(form.elements[k].type==='checkbox')form.elements[k].checked=Boolean(val);else form.elements[k].value=val??''}}preview.innerHTML=(v.images||[]).map(src=>`<img src="${esc(src)}" alt="Foto attuale">`).join('');document.querySelector('#modal-kicker').textContent='MODIFICA AUTO';document.querySelector('#modal-title').textContent=`${v.brand} ${v.model}`;dialog.showModal()}
  document.querySelector('#new-vehicle').onclick=openNew;document.querySelector('#close-dialog').onclick=()=>dialog.close();document.querySelector('#cancel-dialog').onclick=()=>dialog.close();
  list.addEventListener('click',async e=>{const edit=e.target.dataset.edit,del=e.target.dataset.delete;if(edit)openEdit(vehicles.find(v=>v.id===edit));if(del&&confirm('Vuoi eliminare definitivamente questa auto dal sito?')){try{await api(`/api/admin/vehicles/${del}`,{method:'DELETE'});await load()}catch(err){alert(err.message)}}});
  form.images.addEventListener('change',()=>{preview.innerHTML='';[...form.images.files].slice(0,10).forEach(file=>{const img=document.createElement('img');img.src=URL.createObjectURL(file);preview.appendChild(img)})});
  form.addEventListener('submit',async e=>{e.preventDefault();formStatus.textContent='Salvataggio in corso...';const data=new FormData(form);data.set('active',String(form.active.checked));const id=form.elements.id.value;try{await api(id?`/api/admin/vehicles/${id}`:'/api/admin/vehicles',{method:id?'PUT':'POST',body:data});dialog.close();formStatus.textContent='';await load()}catch(err){formStatus.textContent=err.message}});
  check();
})();
